# Deploys the coach service.

service: chess-dojo-coach
frameworkVersion: '3'

plugins:
  - serverless-plugin-custom-roles
  - serverless-go-plugin

provider:
  name: aws
  runtime: provided.al2
  architecture: arm64
  region: us-east-1
  logRetentionInDays: 14
  environment:
    stage: ${sls:stage}
  httpApi:
    id: ${param:httpApiId}

custom:
  go:
    binDir: bin
    cmd: GOARCH=arm64 GOOS=linux go build -tags lambda.norpc -ldflags="-s -w"
    supportedRuntimes: ['provided.al2']
    buildProvidedRuntimeAsBootstrap: true

functions:
  list:
    handler: list/main.go
    events:
      - httpApi:
          path: /public/coach
          method: get
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:BatchGetItem
        Resource: ${param:UsersTableArn}
    environment:
      coaches: ${file(../config-${sls:stage}.yml):coaches}
