# Deploys the DojoAI service.

service: dojoaibot

plugins:
  - serverless-plugin-custom-roles
  - serverless-esbuild

package:
  individually: true

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  logRetentionInDays: 14
  environment:
    stage: ${sls:stage}
  httpApi:
    id: ${param:httpApiId}
  deploymentMethod: direct

functions:
  chat:
    handler: chat.handler
    timeout: 180
    events:
      - httpApi:
          path: /dojoai/chat
          method: post
    environment:
      endpoint: ${file(../ai.yml):endpoint}
      agent: ${file(../ai.yml):agent}

  history:
    handler: chathistory.handler
    events:
      - httpApi:
          path: /dojoai/threadhistory
          method: get
    environment:
      endpoint: ${file(../ai.yml):endpoint}
      agent: ${file(../ai.yml):agent}
