# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/frontend' # Location of package manifests
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 20
    target-branch: dev
    groups:
      amplify:
        applies-to: version-updates
        patterns:
          - '@aws-amplify/*'
          - aws-amplify
      mui:
        applies-to: version-updates
        patterns:
          - '@mui/*'
      fortawesome:
        applies-to: version-updates
        patterns:
          - '@fortawesome/*'
      dev-dependencies:
        applies-to: version-updates
        patterns:
          - eslint-plugin*
          - typescript-eslint
          - '@typescript-eslint/*'
          - happy-dom
          - nodemon
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/backend' # Location of package manifests
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    target-branch: dev
