stage: simple
frontendHost: 'http://localhost:3000'
mobileHost: 'exp://127.0.0.1:8081/--/'
discordFindGameChannelId: ''
discordPrivateGuildId: ''
discordPublicGuildId: ''
discordCoachingChannelId: ''
discordGraduationsChannelId: ''
discordAchievementsChannelId: ''
monthlySubscriptionPriceId: ''
yearlySubscriptionPriceId: ''
quickGameReviewPriceId: ''
deepGameReviewPriceId: ''
hostedZoneId: ''
cognitoUserPoolDomain: ''
coaches: ''
