services:
  chess-dojo-scheduler:
    path: root

  users:
    path: user
    params:
      httpApiId: ${chess-dojo-scheduler.HttpApiId}
      apiAuthorizer: ${chess-dojo-scheduler.serviceAuthorizer}
      UserPoolArn: ${chess-dojo-scheduler.UserPoolArn}
      UserPoolId: ${chess-dojo-scheduler.UserPoolId}
      UsersTableArn: ${chess-dojo-scheduler.UsersTableArn}
      RequirementsTableArn: ${chess-dojo-scheduler.RequirementsTableArn}
      TimelineTableArn: ${chess-dojo-scheduler.TimelineTableArn}
      GraduationsTableArn: ${chess-dojo-scheduler.GraduationsTableArn}
      NotificationsTableArn: ${chess-dojo-scheduler.NotificationsTableArn}
      FollowersTableArn: ${chess-dojo-scheduler.FollowersTableArn}
      PicturesBucket: ${chess-dojo-scheduler.PicturesBucket}
      SecretsBucket: ${chess-dojo-scheduler.SecretsBucket}
      AlertNotificationsTopic: ${chess-dojo-scheduler.AlertNotificationsTopic}

  coach:
    path: coach
    params:
      httpApiId: ${chess-dojo-scheduler.HttpApiId}
      UsersTableArn: ${chess-dojo-scheduler.UsersTableArn}

  scoreboard:
    path: scoreboard
    params:
      httpApiId: ${chess-dojo-scheduler.HttpApiId}
      apiAuthorizer: ${chess-dojo-scheduler.serviceAuthorizer}
      UsersTableArn: ${chess-dojo-scheduler.UsersTableArn}
      FollowersTableArn: ${chess-dojo-scheduler.FollowersTableArn}

  requirements:
    path: requirement
    params:
      httpApiId: ${chess-dojo-scheduler.HttpApiId}
      apiAuthorizer: ${chess-dojo-scheduler.serviceAuthorizer}
      RequirementsTableArn: ${chess-dojo-scheduler.RequirementsTableArn}

  graduations:
    path: graduation
    params:
      httpApiId: ${chess-dojo-scheduler.HttpApiId}
      apiAuthorizer: ${chess-dojo-scheduler.serviceAuthorizer}
      GraduationsTableArn: ${chess-dojo-scheduler.GraduationsTableArn}

  courseService:
    path: courseService
    params:
      httpApiId: ${chess-dojo-scheduler.HttpApiId}
      apiAuthorizer: ${chess-dojo-scheduler.serviceAuthorizer}
      UsersTableArn: ${chess-dojo-scheduler.UsersTableArn}

  newsfeed:
    path: newsfeed
    params:
      httpApiId: ${chess-dojo-scheduler.HttpApiId}
      apiAuthorizer: ${chess-dojo-scheduler.serviceAuthorizer}
      TimelineTableStreamArn: ${chess-dojo-scheduler.TimelineTableStreamArn}
      FollowersTableStreamArn: ${chess-dojo-scheduler.FollowersTableStreamArn}
      NewsfeedTableArn: ${chess-dojo-scheduler.NewsfeedTableArn}
      FollowersTableArn: ${chess-dojo-scheduler.FollowersTableArn}
      TimelineTableArn: ${chess-dojo-scheduler.TimelineTableArn}
      UsersTableArn: ${chess-dojo-scheduler.UsersTableArn}
      NotificationsTableArn: ${chess-dojo-scheduler.NotificationsTableArn}

  tournaments:
    path: tournament
    params:
      httpApiId: ${chess-dojo-scheduler.HttpApiId}
      apiAuthorizer: ${chess-dojo-scheduler.serviceAuthorizer}
      EventsTableArn: ${chess-dojo-scheduler.EventsTableArn}
      TournamentsTableArn: ${chess-dojo-scheduler.TournamentsTableArn}
      UsersTableArn: ${chess-dojo-scheduler.UsersTableArn}
      SecretsBucket: ${chess-dojo-scheduler.SecretsBucket}
      AlertNotificationsTopic: ${chess-dojo-scheduler.AlertNotificationsTopic}

  events:
    path: event
    params:
      httpApiId: ${chess-dojo-scheduler.HttpApiId}
      apiAuthorizer: ${chess-dojo-scheduler.serviceAuthorizer}
      EventsTableArn: ${chess-dojo-scheduler.EventsTableArn}
      EventsTableStreamArn: ${chess-dojo-scheduler.EventsTableStreamArn}
      UsersTableArn: ${chess-dojo-scheduler.UsersTableArn}

  games:
    path: game
    params:
      httpApiId: ${chess-dojo-scheduler.HttpApiId}
      apiAuthorizer: ${chess-dojo-scheduler.serviceAuthorizer}
      GamesTableArn: ${chess-dojo-scheduler.GamesTableArn}
      UsersTableArn: ${chess-dojo-scheduler.UsersTableArn}
      TimelineTableArn: ${chess-dojo-scheduler.TimelineTableArn}
      NotificationsTableArn: ${chess-dojo-scheduler.NotificationsTableArn}
      GameDatabaseBucket: ${chess-dojo-scheduler.GameDatabaseBucket}
      AlertNotificationsTopic: ${chess-dojo-scheduler.AlertNotificationsTopic}

  paymentService:
    path: paymentService
    params:
      httpApiId: ${chess-dojo-scheduler.HttpApiId}
      apiAuthorizer: ${chess-dojo-scheduler.serviceAuthorizer}
      UsersTableArn: ${chess-dojo-scheduler.UsersTableArn}
      EventsTableArn: ${chess-dojo-scheduler.EventsTableArn}
      GamesTableArn: ${chess-dojo-scheduler.GamesTableArn}

  pgnService:
    path: pgnService
    params:
      httpApiId: ${chess-dojo-scheduler.HttpApiId}
      apiAuthorizer: ${chess-dojo-scheduler.serviceAuthorizer}
      UsersTableArn: ${chess-dojo-scheduler.UsersTableArn}
      TournamentsTableArn: ${chess-dojo-scheduler.TournamentsTableArn}
      GamesTableStreamArn: ${chess-dojo-scheduler.GamesTableStreamArn}
      NotificationsTableArn: ${chess-dojo-scheduler.NotificationsTableArn}
      GamesTableArn: ${chess-dojo-scheduler.GamesTableArn}
      TimelineTableArn: ${chess-dojo-scheduler.TimelineTableArn}

  emailService:
    path: email
    params:
      httpApiId: ${chess-dojo-scheduler.HttpApiId}
      apiAuthorizer: ${chess-dojo-scheduler.serviceAuthorizer}
      SecretsBucket: ${chess-dojo-scheduler.SecretsBucket}

  yearReviewService:
    path: yearReviewService
    params:
      httpApiId: ${chess-dojo-scheduler.HttpApiId}

  clubService:
    path: clubService
    params:
      httpApiId: ${chess-dojo-scheduler.HttpApiId}
      apiAuthorizer: ${chess-dojo-scheduler.serviceAuthorizer}
      UsersTableArn: ${chess-dojo-scheduler.UsersTableArn}
      NotificationsTableArn: ${chess-dojo-scheduler.NotificationsTableArn}
      PicturesBucket: ${chess-dojo-scheduler.PicturesBucket}

  examService:
    path: examService
    params:
      httpApiId: ${chess-dojo-scheduler.HttpApiId}
      apiAuthorizer: ${chess-dojo-scheduler.serviceAuthorizer}
      UsersTableArn: ${chess-dojo-scheduler.UsersTableArn}
