import {
    Alarm,
    AllInclusiveRounded,
    AutoStories,
    Backup,
    Biotech,
    BorderColor,
    CalendarMonth,
    Create,
    CrisisAlert,
    DashboardCustomize,
    DoDisturb,
    Download,
    EditCalendar,
    Event,
    EventAvailable,
    Explore,
    FlashOn,
    GridView,
    Group,
    Groups,
    Info,
    Leaderboard,
    LiveTv,
    LocalHospital,
    LocationOn,
    Login,
    MenuBook,
    MilitaryTech,
    Notes,
    PeopleOutline,
    Person,
    PersonOutline,
    PunchClock,
    QueryBuilder,
    RestartAlt,
    RocketLaunch,
    Save,
    Science,
    Search,
    Speed,
    SportsScore,
    Stadium,
    ThumbUp,
    Visibility,
    WavingHand,
    Whatshot,
} from '@mui/icons-material';
import { SvgIconProps } from '@mui/material';
import React from 'react';
import { AvailabilityType, EventType, TimeControlType, TournamentType } from '../database/event';
import { RequirementCategory } from '../database/requirement';
import RookIcon from './RookIcon';
export const icons = {
    [RequirementCategory.Welcome]: WavingHand,
    [RequirementCategory.Games]: Biotech,
    [RequirementCategory.Tactics]: Speed,
    [RequirementCategory.Middlegames]: MenuBook,
    [RequirementCategory.Endgame]: SportsScore,
    [RequirementCategory.Opening]: CrisisAlert,
    [RequirementCategory.NonDojo]: LiveTv,
    Annotations: BorderColor,
    Followers: ThumbUp,
    followers: ThumbUp,
    'All Categories': AllInclusiveRounded,
    clubs: Groups,
    search: Search,
    explore: Explore,
    cohort: Group,
    player: Person,
    upload: Backup,
    line: PeopleOutline,
    download: Download,
    eye: Visibility,
    clock: QueryBuilder,
    eventCheck: EventAvailable,
    liga: MilitaryTech,
    meet: Event,
    all: AllInclusiveRounded,
    'All Types': AllInclusiveRounded,
    Blitz: Whatshot,
    Rapid: FlashOn,
    Classical: PunchClock,
    [TimeControlType.Blitz]: Whatshot,
    [TimeControlType.Rapid]: FlashOn,
    [TimeControlType.Classical]: PunchClock,
    [TimeControlType.AllTimeContols]: AllInclusiveRounded,
    'Classical Game': PunchClock,
    'Dojo Events': LiveTv,
    'Coaching Sessions': RocketLaunch,
    avilb: EditCalendar,
    [AvailabilityType.ClassicalGame]: PunchClock,
    [AvailabilityType.OpeningSparring]: CrisisAlert,
    [AvailabilityType.MiddlegameSparring]: MenuBook,
    [AvailabilityType.EndgameSparring]: SportsScore,
    [AvailabilityType.RookEndgameProgression]: RookIcon,
    [AvailabilityType.ClassicAnalysis]: Science,
    [AvailabilityType.AnalyzeOwnGame]: Biotech,
    [AvailabilityType.BookStudy]: AutoStories,
    [AvailabilityType.AllTypes]: AllInclusiveRounded,
    'Opening Sparring': CrisisAlert,
    'Middlegame Sparring': MenuBook,
    'Endgame Sparring': SportsScore,
    'Analyze Classic Game': Science,
    'Analyze Own Game': Biotech,
    'Book Study': AutoStories,
    'Rook Endgame Progression': RookIcon,
    reset: RestartAlt,
    cancel: DoDisturb,
    save: Save,
    location: LocationOn,
    write: Create,
    join: Login,
    notes: Notes,
    participant: PersonOutline,
    [TournamentType.Arena]: Stadium,
    [TournamentType.Swiss]: LocalHospital,
    Swiss: LocalHospital,
    Arena: Stadium,
    tc: Alarm,
    Standard: GridView,
    Custom: DashboardCustomize,
    ligaCalendar: CalendarMonth,
    leaderboard: Leaderboard,
    info: Info,
    [EventType.Availability]: Event,
    [EventType.Coaching]: RocketLaunch,
    [EventType.Dojo]: LiveTv,
    [EventType.LigaTournament]: MilitaryTech,
};

export interface IconProps extends SvgIconProps {
    name: keyof typeof icons | '';
}

export const Icon: React.FC<IconProps> = ({ name, ...props }) => {
    if (!name || !icons[name]) {
        return null;
    }

    const InternalIcon = icons[name];
    return <InternalIcon {...props} />;
};

export default Icon;
