export interface Position {
    title: string;
    fen: string;
    link: string;
    limitSeconds: number;
    incrementSeconds: number;
}

export interface CohortPositions {
    cohort: string;
    positions: Position[];
}

export interface PositionSection {
    title: string;
    cohorts: CohortPositions[];
}

export const sections: PositionSection[] = [
    {
        title: 'Middlegame Win Conversions',
        cohorts: [
            {
                cohort: '600-1000',
                positions: [
                    {
                        title: '#1: Extra Queen',
                        fen: '2r2rk1/pb1nbppp/1p2pn2/2pp4/3P1B2/2PBPN2/PP3PPP/RN1QR1K1 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10522617',
                        limitSeconds: 300,
                        incrementSeconds: 5,
                    },
                    {
                        title: '#2: Extra Rook',
                        fen: 'r2qk2B/pbp1bp1p/1p2pn2/3p4/8/1P1P1N2/P1P1BPPP/RN1Q1RK1 w q - 0 1',
                        link: '//www.chess.com/emboard?id=10522621',
                        limitSeconds: 300,
                        incrementSeconds: 5,
                    },
                    {
                        title: '#3: Two Extra Pieces',
                        fen: 'r2qk2r/pbp2ppp/1p2pn2/3pN3/3Q4/8/PPP1BPPP/RNB2RK1 w kq - 0 1',
                        link: '//www.chess.com/emboard?id=10522627',
                        limitSeconds: 300,
                        incrementSeconds: 5,
                    },
                    {
                        title: '#4: One Extra Piece',
                        fen: '3q1rk1/p1pn1ppp/1p1b1n2/6N1/8/2N2Q2/PPP2PPP/R1B1R1K1 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10522633',
                        limitSeconds: 300,
                        incrementSeconds: 5,
                    },
                ],
            },
        ],
    },
    {
        title: 'Middlegame Sparring',
        cohorts: [
            {
                cohort: '1000-1100',
                positions: [
                    {
                        title: '#1: Alekhine - NN',
                        fen: 'r1bqnrk1/ppppnppp/1b6/3PP3/2B5/5N2/PP3PPP/RNBQ1RK1 w - - 0 10',
                        link: '//www.chess.com/emboard?id=10526059',
                        limitSeconds: 900,
                        incrementSeconds: 10,
                    },
                ],
            },
            {
                cohort: '1100-1200',
                positions: [
                    {
                        title: '#1: Marshall - Chigorin',
                        fen: '2rqr1k1/pp3ppp/5nn1/8/2NP4/P2Q4/1B3PPP/R4RK1 w - - 0 19',
                        link: '//www.chess.com/emboard?id=10526067',
                        limitSeconds: 900,
                        incrementSeconds: 10,
                    },
                ],
            },
            {
                cohort: '1200-1300',
                positions: [
                    {
                        title: '#1: Steinitz - Paulsen',
                        fen: '2kr1bnr/ppp2ppp/2np4/8/3PPB1q/P1N1K3/1PP1B1PP/R2Q3R w - - 0 13',
                        link: '//www.chess.com/emboard?id=10526073',
                        limitSeconds: 900,
                        incrementSeconds: 10,
                    },
                ],
            },
            {
                cohort: '1300-1400',
                positions: [
                    {
                        title: '#1: Kline - Capablanca',
                        fen: 'r1b1rnk1/pp3ppp/2p2q2/4p2n/4P3/2PBNN2/PPQ2PPP/R4RK1 w - - 0 16',
                        link: '//www.chess.com/emboard?id=10526101',
                        limitSeconds: 900,
                        incrementSeconds: 10,
                    },
                ],
            },
            {
                cohort: '1400-1500',
                positions: [
                    {
                        title: '#1: Stein - Furman',
                        fen: 'rn1k1b1r/1bq2ppp/p2p1n2/3P4/Pp1N4/6P1/1PP2PBP/R1BQR1K1 w - - 0 13',
                        link: '//www.chess.com/emboard?id=10526109',
                        limitSeconds: 900,
                        incrementSeconds: 10,
                    },
                    {
                        title: '#2: Rosenthal - Steinitz',
                        fen: 'r1br2k1/ppp2pbp/6p1/8/2qN1P2/2P1B3/PPQ3PP/R4RK1 w - - 0 16',
                        link: '//www.chess.com/emboard?id=10526115',
                        limitSeconds: 900,
                        incrementSeconds: 10,
                    },
                ],
            },
            {
                cohort: '1500-1600',
                positions: [
                    {
                        title: '#1: Knorre - Chigorin',
                        fen: 'r1bqk2r/ppp2N2/2np1n2/2b1p3/2B1P3/3P2p1/PPP2PPP/RN1Q1RK1 w kq - 0 11',
                        link: '//www.chess.com/emboard?id=10526123',
                        limitSeconds: 900,
                        incrementSeconds: 10,
                    },
                    {
                        title: '#2: Gunsberg - Chigorin',
                        fen: 'r4rk1/2p2pbp/p1nqbnp1/1p2p3/3pP1P1/2PP1N1P/PPBNQP2/R1B1K2R w KQ - 0 14',
                        link: '//www.chess.com/emboard?id=10526125',
                        limitSeconds: 900,
                        incrementSeconds: 10,
                    },
                ],
            },
            {
                cohort: '1600-1700',
                positions: [
                    {
                        title: '#1: Keres - Sajtar',
                        fen: 'r1b1kb1r/1p1n2pp/p2pNn2/6B1/2q1P3/2N5/PPP2PPP/R2Q1RK1 w kq - 0 11',
                        link: '//www.chess.com/emboard?id=10526129',
                        limitSeconds: 900,
                        incrementSeconds: 10,
                    },
                    {
                        title: '#2: Lasker - Steinitz',
                        fen: 'r1b2rk1/6pp/1qpp1p1n/pp2p3/4P3/1P1PPNNP/1PPQ2P1/4RRK1 w - - 0 18',
                        link: '//www.chess.com/emboard?id=10526131',
                        limitSeconds: 900,
                        incrementSeconds: 10,
                    },
                ],
            },
            {
                cohort: '1700-1800',
                positions: [
                    {
                        title: '#1: Nimzowitsch - Capablanca',
                        fen: '2r1r1k1/2pq1pbp/Q1pp1np1/8/4P3/2N5/PPP2PPP/R1B2RK1 w - - 0 15',
                        link: '//www.chess.com/emboard?id=10526143',
                        limitSeconds: 900,
                        incrementSeconds: 10,
                    },
                    {
                        title: '#2: Romanishin - Petrosian',
                        fen: '1q2rrk1/1b2bp1p/pp1p1np1/3P4/2PQ1P2/1P3R2/PBB3PP/2R4K w - - 0 19',
                        link: '//www.chess.com/emboard?id=10526153',
                        limitSeconds: 900,
                        incrementSeconds: 10,
                    },
                ],
            },
            {
                cohort: '1800-1900',
                positions: [
                    {
                        title: '#1: Bondarevsky - Lilienthal',
                        fen: 'r1br2k1/pp2qppp/3pnn2/2p1p3/3PP3/2P2N2/P1P2PPP/R1BQRBK1 w - - 0 13',
                        link: '//www.chess.com/emboard?id=10526163',
                        limitSeconds: 900,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#2: Lipnitsky - Kotlerman',
                        fen: '1rbq1rk1/3nbppp/p1p1p3/3p2PP/4PP2/2N1B3/PPPQB3/2KR3R w - - 0 16',
                        link: '//www.chess.com/emboard?id=10526169',
                        limitSeconds: 900,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#3: Petrosian - Smyslov',
                        fen: '2rr2k1/1bqnbppp/p2p1n2/1p2pP2/4P3/P1N1BB2/1PPN2PP/R2Q1R1K w - - 0 16',
                        link: '//www.chess.com/emboard?id=10526171',
                        limitSeconds: 900,
                        incrementSeconds: 30,
                    },
                ],
            },
            {
                cohort: '1900-2000',
                positions: [
                    {
                        title: '#1: Koenig - Smyslov',
                        fen: 'r1b2rk1/5ppp/pnqp1b2/np2p3/4P3/2P2N1P/PPB2PP1/R1BQRNK1 w - - 0 16',
                        link: '//www.chess.com/emboard?id=10526173',
                        limitSeconds: 900,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#2: Fischer - Myagmarsuren',
                        fen: 'r2q1rk1/3nbppp/b3p3/n1ppP3/p4B1P/P2PNNP1/2P2PB1/R2QR1K1 w - - 0 16',
                        link: '//www.chess.com/emboard?id=10526179',
                        limitSeconds: 900,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#3: Fischer - Larsen',
                        fen: '5rk1/p1r1ppbp/3p1np1/q7/1p1BP3/1B3P2/PPPQ2PP/1K1R3R w - - 0 17',
                        link: '//www.chess.com/emboard?id=10526183',
                        limitSeconds: 900,
                        incrementSeconds: 30,
                    },
                ],
            },
            {
                cohort: '2000-2100',
                positions: [
                    {
                        title: '#1: Saemisch - Alekhine',
                        fen: 'r2r2k1/pb3pp1/3ppq1p/2p5/2P5/3BP3/PPQ2PPP/3R1RK1 w - - 0 17',
                        link: '//www.chess.com/emboard?id=10526189',
                        limitSeconds: 900,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#2: Thomas - Alekhine',
                        fen: 'r4rk1/pq2ppbp/1p4p1/8/3p1P2/3P4/PPP3PP/R1B1QR1K w - - 0 18',
                        link: '//www.chess.com/emboard?id=10526193',
                        limitSeconds: 900,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#3: Alekhine - Yates',
                        fen: 'r2qr1k1/pb1nbppp/1p3n2/3p2B1/3N3P/2NBP3/PPQ2PP1/2KR3R w - - 0 13',
                        link: '//www.chess.com/emboard?id=10526197',
                        limitSeconds: 900,
                        incrementSeconds: 30,
                    },
                ],
            },
            {
                cohort: '2100-2200',
                positions: [
                    {
                        title: '#1: Pilnik - Geller',
                        fen: 'r2r2k1/pb3pp1/3ppq1p/2p5/2P5/3BP3/PPQ2PPP/3R1RK1 w - - 0 17',
                        link: '//www.chess.com/emboard?id=10526199',
                        limitSeconds: 900,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#2: Smyslov - Reshevksy',
                        fen: 'r3r1k1/1pp1qpp1/p1n3np/3Rp3/4P3/1BP2Q2/PP3PPP/R1B3K1 w - - 0 18',
                        link: '//www.chess.com/emboard?id=10526207',
                        limitSeconds: 900,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#3: Taimanov - Averbakh',
                        fen: '3q1rk1/pbr2ppp/1p2pn2/2p1N3/2PPn3/P2BP3/1B3PPP/R2QR1K1 w - - 0 16',
                        link: '//www.chess.com/emboard?id=10526213',
                        limitSeconds: 900,
                        incrementSeconds: 30,
                    },
                ],
            },
            {
                cohort: '2200-2300',
                positions: [
                    {
                        title: '#1: Alatortsev - Levenfish',
                        fen: 'r1b2rk1/p1p1q1pp/1p1p4/3Pn3/2P1Pp2/3N1P2/PP4BP/2RQR1K1 w - - 0 19',
                        link: '//www.chess.com/emboard?id=10526215',
                        limitSeconds: 900,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#2: Alekhine - Lasker',
                        fen: 'r1bqrnk1/pp3ppp/2pb4/3p4/3P1P2/2NB1NP1/PPQ2P1P/R4RK1 w - - 0 13',
                        link: '//www.chess.com/emboard?id=10526219',
                        limitSeconds: 900,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#3: Smyslov - Keres',
                        fen: 'rqrb2k1/n2b1p1p/p2p1np1/1p1Pp3/1P2P2N/1N1B1Q1P/P2B1PP1/R3R1K1 w - - 0 23',
                        link: '//www.chess.com/emboard?id=10526223',
                        limitSeconds: 900,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#4: Tal - Tolush',
                        fen: 'r1b1r1k1/1p1n1pbp/p2p1np1/q1pPp1B1/2P1P1PP/2N2PN1/PP1Q4/R3KB1R w KQ - 0 13',
                        link: '//www.chess.com/emboard?id=10526231',
                        limitSeconds: 900,
                        incrementSeconds: 30,
                    },
                ],
            },
            {
                cohort: '2300-2400',
                positions: [
                    {
                        title: '#1: Smyslov - Reshevsky',
                        fen: '3rr1k1/2q2pp1/1p1p1np1/p1n1p3/2P5/1P2QPPB/PB1RP2P/3R2K1 w - - 0 21',
                        link: '//www.chess.com/emboard?id=10526235',
                        limitSeconds: 900,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#2: Petrosian - Smyslov',
                        fen: 'r2qk2r/pb2bp2/1n2p1p1/1p2P1Np/2pP3P/2P3Q1/4BPP1/R1B1K2R w KQkq - 0 16',
                        link: '//www.chess.com/emboard?id=10526241',
                        limitSeconds: 900,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#3: Karpov - Spassky',
                        fen: 'r4rk1/2b2pp1/p1p3qp/PpN5/1PnPN3/6Pb/4BP1P/2RQR1K1 w - - 0 24',
                        link: '//www.chess.com/emboard?id=10526247',
                        limitSeconds: 900,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#4: Spassky - Fischer',
                        fen: 'r1b1qrk1/1pp1ppbp/1n4p1/p3P3/4N3/5N1P/1PP1QPP1/R1B1R1K1 w - - 0 16',
                        link: '//www.chess.com/emboard?id=10526255',
                        limitSeconds: 900,
                        incrementSeconds: 30,
                    },
                ],
            },
            {
                cohort: '2400+',
                positions: [
                    {
                        title: '#1: Spassky - Petrosian',
                        fen: '3rr1k1/2q2pp1/1p1p1np1/p1n1p3/2P5/1P2QPPB/PB1RP2P/3R2K1 w - - 0 21',
                        link: '//www.chess.com/emboard?id=10526261',
                        limitSeconds: 900,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#2: Capablanca - Fine',
                        fen: 'r1q2rk1/pp1b1ppp/5b2/3Q4/8/2N1PN2/PP3PPP/R3K2R w KQ - 0 13',
                        link: '//www.chess.com/emboard?id=10526263',
                        limitSeconds: 900,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#3: Kasparov - Grischuk',
                        fen: 'r2q1rk1/3bbppp/pn1p1n2/2pPp3/PpP1P3/1P3N1P/2B1QPP1/RNB1R1K1 w - - 0 17',
                        link: '//www.chess.com/emboard?id=10526267',
                        limitSeconds: 900,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#4: McShane - Carlsen',
                        fen: 'r1bqr1k1/1pp1b1pp/p3np2/2p1p3/4P2N/1P1P4/PBP1NPPP/R2Q1R1K w - - 0 14',
                        link: '//www.chess.com/emboard?id=10526281',
                        limitSeconds: 900,
                        incrementSeconds: 30,
                    },
                ],
            },
        ],
    },
    {
        title: 'Endgame Algorithms',
        cohorts: [
            {
                cohort: '0-500',
                positions: [
                    {
                        title: '#1: K+Q Checkmate',
                        fen: '8/8/8/8/8/1k6/8/QK6 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362279',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                ],
            },
            {
                cohort: '500-600',
                positions: [
                    {
                        title: '#1: K+Q Checkmate',
                        fen: '8/8/8/8/8/1k6/8/QK6 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362279',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#2: K+R Checkmate',
                        fen: '8/8/8/8/8/1k6/8/RK6 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362283',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                ],
            },
            {
                cohort: '600-700',
                positions: [
                    {
                        title: '#1: K+Q Checkmate',
                        fen: '8/8/8/8/8/1k6/8/QK6 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362279',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#2: K+R Checkmate',
                        fen: '8/8/8/8/8/1k6/8/RK6 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362283',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                ],
            },
            {
                cohort: '700-800',
                positions: [
                    {
                        title: '#1: K+Q Checkmate',
                        fen: '8/8/8/8/8/1k6/8/QK6 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362279',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#2: K+R Checkmate',
                        fen: '8/8/8/8/8/1k6/8/RK6 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362283',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#3: K+P vs K',
                        fen: '3k4/8/8/8/8/8/3P4/3K4 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362289',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                ],
            },
            {
                cohort: '800-900',
                positions: [
                    {
                        title: '#1: K+Q Checkmate',
                        fen: '8/8/8/8/8/1k6/8/QK6 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362279',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#2: K+R Checkmate',
                        fen: '8/8/8/8/8/1k6/8/RK6 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362283',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#3: K+P vs K',
                        fen: '3k4/8/8/8/8/8/3P4/3K4 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362289',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#4: Two Bishop Checkmate',
                        fen: '3k4/8/8/8/8/8/8/B2K1B2 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362291',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                ],
            },
            {
                cohort: '900-1000',
                positions: [
                    {
                        title: '#1: K+Q Checkmate',
                        fen: '8/8/8/8/8/1k6/8/QK6 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362279',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#2: K+R Checkmate',
                        fen: '8/8/8/8/8/1k6/8/RK6 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362283',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#3: K+P vs K',
                        fen: '3k4/8/8/8/8/8/3P4/3K4 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362289',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#4: Two Bishop Checkmate',
                        fen: '3k4/8/8/8/8/8/8/B2K1B2 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362291',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                ],
            },
            {
                cohort: '1000-1100',
                positions: [
                    {
                        title: '#2: K+R Checkmate',
                        fen: '8/8/8/8/8/1k6/8/RK6 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362283',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#3: K+P vs K',
                        fen: '3k4/8/8/8/8/8/3P4/3K4 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362289',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#4: Two Bishop Checkmate',
                        fen: '3k4/8/8/8/8/8/8/B2K1B2 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362291',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#5: K+P 2',
                        fen: '8/2k5/1p6/1P1K4/8/8/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362295',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                ],
            },
            {
                cohort: '1100-1200',
                positions: [
                    {
                        title: '#3: K+P vs K',
                        fen: '3k4/8/8/8/8/8/3P4/3K4 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362289',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#4: Two Bishop Checkmate',
                        fen: '3k4/8/8/8/8/8/8/B2K1B2 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362291',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#5: K+P 2',
                        fen: '8/2k5/1p6/1P1K4/8/8/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362295',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#6: K+P 3',
                        fen: '8/8/8/6p1/5kP1/8/5K2/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362299',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                ],
            },
            {
                cohort: '1200-1300',
                positions: [
                    {
                        title: '#3: K+P vs K',
                        fen: '3k4/8/8/8/8/8/3P4/3K4 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362289',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#4: Two Bishop Checkmate',
                        fen: '3k4/8/8/8/8/8/8/B2K1B2 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362291',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#5: K+P 2',
                        fen: '8/2k5/1p6/1P1K4/8/8/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362295',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#6: K+P 3',
                        fen: '8/8/8/6p1/5kP1/8/5K2/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362299',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                ],
            },
            {
                cohort: '1300-1400',
                positions: [
                    {
                        title: '#3: K+P vs K',
                        fen: '3k4/8/8/8/8/8/3P4/3K4 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362289',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#4: Two Bishop Checkmate',
                        fen: '3k4/8/8/8/8/8/8/B2K1B2 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362291',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#5: K+P 2',
                        fen: '8/2k5/1p6/1P1K4/8/8/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362295',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#6: K+P 3',
                        fen: '8/8/8/6p1/5kP1/8/5K2/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362299',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                ],
            },
            {
                cohort: '1400-1500',
                positions: [
                    {
                        title: '#3: K+P vs K',
                        fen: '3k4/8/8/8/8/8/3P4/3K4 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362289',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#4: Two Bishop Checkmate',
                        fen: '3k4/8/8/8/8/8/8/B2K1B2 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362291',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#5: K+P 2',
                        fen: '8/2k5/1p6/1P1K4/8/8/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362295',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#6: K+P 3',
                        fen: '8/8/8/6p1/5kP1/8/5K2/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362299',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                ],
            },
            {
                cohort: '1500-1600',
                positions: [
                    {
                        title: '#4: Two Bishop Checkmate',
                        fen: '3k4/8/8/8/8/8/8/B2K1B2 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362291',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#5: K+P 2',
                        fen: '8/2k5/1p6/1P1K4/8/8/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362295',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#6: K+P 3',
                        fen: '8/8/8/6p1/5kP1/8/5K2/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362299',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#7: Philidor',
                        fen: '1R6/8/8/8/4pk2/8/r7/4K3 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362301',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#8: Lucena',
                        fen: '3K4/3P1k2/8/8/8/8/2r5/4R3 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362305',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#9: K+P 4',
                        fen: '2k5/8/p1P5/P2K4/8/8/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362313',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                ],
            },
            {
                cohort: '1600-1700',
                positions: [
                    {
                        title: '#5: K+P 2',
                        fen: '8/2k5/1p6/1P1K4/8/8/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362295',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#6: K+P 3',
                        fen: '8/8/8/6p1/5kP1/8/5K2/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362299',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#7: Philidor',
                        fen: '1R6/8/8/8/4pk2/8/r7/4K3 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362301',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#8: Lucena',
                        fen: '3K4/3P1k2/8/8/8/8/2r5/4R3 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362305',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#9: K+P 4',
                        fen: '2k5/8/p1P5/P2K4/8/8/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362313',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#10: B+N Checkmate',
                        fen: '5k2/5N2/5K2/5B2/8/8/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362315',
                        limitSeconds: 300,
                        incrementSeconds: 0,
                    },
                ],
            },
            {
                cohort: '1700-1800',
                positions: [
                    {
                        title: '#5: K+P 2',
                        fen: '8/2k5/1p6/1P1K4/8/8/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362295',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#6: K+P 3',
                        fen: '8/8/8/6p1/5kP1/8/5K2/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362299',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#7: Philidor',
                        fen: '1R6/8/8/8/4pk2/8/r7/4K3 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362301',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#8: Lucena',
                        fen: '3K4/3P1k2/8/8/8/8/2r5/4R3 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362305',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#9: K+P 4',
                        fen: '2k5/8/p1P5/P2K4/8/8/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362313',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#10: B+N Checkmate',
                        fen: '5k2/5N2/5K2/5B2/8/8/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362315',
                        limitSeconds: 300,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#11: B+N Checkmate 2',
                        fen: '8/8/8/8/8/2k5/8/NBK5 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362319',
                        limitSeconds: 300,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#12: K+P 5',
                        fen: '8/7p/3K1k2/7P/5P2/8/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362323',
                        limitSeconds: 300,
                        incrementSeconds: 0,
                    },
                ],
            },
            {
                cohort: '1800-1900',
                positions: [
                    {
                        title: '#7: Philidor',
                        fen: '1R6/8/8/8/4pk2/8/r7/4K3 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362301',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#8: Lucena',
                        fen: '3K4/3P1k2/8/8/8/8/2r5/4R3 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362305',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#9: K+P 4',
                        fen: '2k5/8/p1P5/P2K4/8/8/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362313',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#10: B+N Checkmate',
                        fen: '5k2/5N2/5K2/5B2/8/8/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362315',
                        limitSeconds: 300,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#11: B+N Checkmate 2',
                        fen: '8/8/8/8/8/2k5/8/NBK5 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362319',
                        limitSeconds: 300,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#12: K+P 5',
                        fen: '8/7p/3K1k2/7P/5P2/8/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362323',
                        limitSeconds: 300,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#13: Q vs P',
                        fen: '5QK1/8/8/8/8/8/1p6/2k5 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362325',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#14: Q vs P 2',
                        fen: '8/6K1/5P2/8/8/8/8/1kq5 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362329',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#15: R vs P',
                        fen: '8/2PK3r/8/3k4/8/8/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362331',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                ],
            },
            {
                cohort: '1900-2000',
                positions: [
                    {
                        title: '#11: B+N Checkmate 2',
                        fen: '8/8/8/8/8/2k5/8/NBK5 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362319',
                        limitSeconds: 300,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#12: K+P 5',
                        fen: '8/7p/3K1k2/7P/5P2/8/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362323',
                        limitSeconds: 300,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#13: Q vs P',
                        fen: '5QK1/8/8/8/8/8/1p6/2k5 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362325',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#14: Q vs P 2',
                        fen: '8/6K1/5P2/8/8/8/8/1kq5 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362329',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#15: R vs P',
                        fen: '8/2PK3r/8/3k4/8/8/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362331',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },

                    {
                        title: '#16: R vs P 2',
                        fen: '8/4K3/8/3pk3/3R4/8/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362337',
                        limitSeconds: 300,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#17: Errant Knight',
                        fen: '8/8/8/7n/3K4/2R5/3k4/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362339',
                        limitSeconds: 300,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#18: Q vs R',
                        fen: '8/8/8/4k3/3r4/8/Q7/1K6 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362341',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#19: R+B vs R',
                        fen: '3k4/4r3/3K4/3B4/8/8/8/5R2 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362345',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#20: R+B vs R 2',
                        fen: '8/8/3K4/r5b1/3k4/8/8/5R2 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362351',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#21: Opposite Bishops',
                        fen: '4bB2/8/4k3/3pp3/8/3K4/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362347',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                ],
            },
            {
                cohort: '2000-2100',
                positions: [
                    {
                        title: '#12: K+P 5',
                        fen: '8/7p/3K1k2/7P/5P2/8/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362323',
                        limitSeconds: 300,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#13: Q vs P',
                        fen: '5QK1/8/8/8/8/8/1p6/2k5 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362325',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#14: Q vs P 2',
                        fen: '8/6K1/5P2/8/8/8/8/1kq5 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362329',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#15: R vs P',
                        fen: '8/2PK3r/8/3k4/8/8/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362331',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },

                    {
                        title: '#16: R vs P 2',
                        fen: '8/4K3/8/3pk3/3R4/8/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362337',
                        limitSeconds: 300,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#17: Errant Knight',
                        fen: '8/8/8/7n/3K4/2R5/3k4/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362339',
                        limitSeconds: 300,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#18: Q vs R',
                        fen: '8/8/8/4k3/3r4/8/Q7/1K6 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362341',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#19: R+B vs R',
                        fen: '3k4/4r3/3K4/3B4/8/8/8/5R2 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362345',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#20: R+B vs R 2',
                        fen: '8/8/3K4/r5b1/3k4/8/8/5R2 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362351',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#21: Opposite Bishops',
                        fen: '4bB2/8/4k3/3pp3/8/3K4/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362347',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                ],
            },
            {
                cohort: '2100-2200',
                positions: [
                    {
                        title: '#14: Q vs P 2',
                        fen: '8/6K1/5P2/8/8/8/8/1kq5 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362329',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#15: R vs P',
                        fen: '8/2PK3r/8/3k4/8/8/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362331',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },

                    {
                        title: '#16: R vs P 2',
                        fen: '8/4K3/8/3pk3/3R4/8/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362337',
                        limitSeconds: 300,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#17: Errant Knight',
                        fen: '8/8/8/7n/3K4/2R5/3k4/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362339',
                        limitSeconds: 300,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#18: Q vs R',
                        fen: '8/8/8/4k3/3r4/8/Q7/1K6 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362341',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#19: R+B vs R',
                        fen: '3k4/4r3/3K4/3B4/8/8/8/5R2 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362345',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#20: R+B vs R 2',
                        fen: '8/8/3K4/r5b1/3k4/8/8/5R2 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362351',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#21: Opposite Bishops',
                        fen: '4bB2/8/4k3/3pp3/8/3K4/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362347',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#22: R+Rp vs B',
                        fen: '8/6k1/8/8/7P/3b2K1/5R2/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362353',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                ],
            },
            {
                cohort: '2200-2300',
                positions: [
                    {
                        title: '#14: Q vs P 2',
                        fen: '8/6K1/5P2/8/8/8/8/1kq5 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362329',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#15: R vs P',
                        fen: '8/2PK3r/8/3k4/8/8/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362331',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },

                    {
                        title: '#16: R vs P 2',
                        fen: '8/4K3/8/3pk3/3R4/8/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362337',
                        limitSeconds: 300,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#17: Errant Knight',
                        fen: '8/8/8/7n/3K4/2R5/3k4/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362339',
                        limitSeconds: 300,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#18: Q vs R',
                        fen: '8/8/8/4k3/3r4/8/Q7/1K6 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362341',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#19: R+B vs R',
                        fen: '3k4/4r3/3K4/3B4/8/8/8/5R2 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362345',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#20: R+B vs R 2',
                        fen: '8/8/3K4/r5b1/3k4/8/8/5R2 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362351',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#21: Opposite Bishops',
                        fen: '4bB2/8/4k3/3pp3/8/3K4/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362347',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#22: R+Rp vs B',
                        fen: '8/6k1/8/8/7P/3b2K1/5R2/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362353',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                ],
            },
            {
                cohort: '2300-2400',
                positions: [
                    {
                        title: '#15: R vs P',
                        fen: '8/2PK3r/8/3k4/8/8/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362331',
                        limitSeconds: 180,
                        incrementSeconds: 0,
                    },

                    {
                        title: '#16: R vs P 2',
                        fen: '8/4K3/8/3pk3/3R4/8/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362337',
                        limitSeconds: 300,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#17: Errant Knight',
                        fen: '8/8/8/7n/3K4/2R5/3k4/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362339',
                        limitSeconds: 300,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#18: Q vs R',
                        fen: '8/8/8/4k3/3r4/8/Q7/1K6 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362341',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#19: R+B vs R',
                        fen: '3k4/4r3/3K4/3B4/8/8/8/5R2 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362345',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#20: R+B vs R 2',
                        fen: '8/8/3K4/r5b1/3k4/8/8/5R2 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362351',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#21: Opposite Bishops',
                        fen: '4bB2/8/4k3/3pp3/8/3K4/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362347',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#22: R+Rp vs B',
                        fen: '8/6k1/8/8/7P/3b2K1/5R2/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362353',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#23: Q vs R+P',
                        fen: '8/8/3pk3/2r5/3K4/5Q2/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362359',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                ],
            },
            {
                cohort: '2400+',
                positions: [
                    {
                        title: '#16: R vs P 2',
                        fen: '8/4K3/8/3pk3/3R4/8/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362337',
                        limitSeconds: 300,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#17: Errant Knight',
                        fen: '8/8/8/7n/3K4/2R5/3k4/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362339',
                        limitSeconds: 300,
                        incrementSeconds: 0,
                    },
                    {
                        title: '#18: Q vs R',
                        fen: '8/8/8/4k3/3r4/8/Q7/1K6 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362341',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#19: R+B vs R',
                        fen: '3k4/4r3/3K4/3B4/8/8/8/5R2 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362345',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#20: R+B vs R 2',
                        fen: '8/8/3K4/r5b1/3k4/8/8/5R2 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362351',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#21: Opposite Bishops',
                        fen: '4bB2/8/4k3/3pp3/8/3K4/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362347',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#22: R+Rp vs B',
                        fen: '8/6k1/8/8/7P/3b2K1/5R2/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362353',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#23: Q vs R+P',
                        fen: '8/8/3pk3/2r5/3K4/5Q2/8/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362359',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#24: 2N vs P',
                        fen: '8/8/2k5/p7/N1K5/8/5N2/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10362363',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                ],
            },
        ],
    },
    {
        title: 'Endgame Win Conversions',
        cohorts: [
            {
                cohort: '600-1000',
                positions: [
                    {
                        title: '#1: Extra Rook',
                        fen: '5k2/p4pp1/4p2p/1p1pP3/7P/8/P4PP1/R5K1 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10528265',
                        limitSeconds: 300,
                        incrementSeconds: 5,
                    },
                    {
                        title: '#2: Extra Bishop',
                        fen: '6k1/1p4pp/p4p2/3p4/3P1B2/1P6/P4PP1/6K1 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10528269',
                        limitSeconds: 300,
                        incrementSeconds: 5,
                    },
                    {
                        title: '#3: Extra Knight',
                        fen: '6k1/1p3pp1/p6p/3p4/3N4/4P2P/P4PP1/6K1 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10528275',
                        limitSeconds: 300,
                        incrementSeconds: 5,
                    },
                    {
                        title: '#4: Extra Exchange',
                        fen: '5k2/5ppp/p2ppn2/1pp5/3P4/1PP1P1P1/P4P1P/R5K1 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10528281',
                        limitSeconds: 300,
                        incrementSeconds: 5,
                    },
                ],
            },
        ],
    },
    {
        title: 'Endgame Positional Sparring',
        cohorts: [
            {
                cohort: '1000-1100',
                positions: [
                    {
                        title: '#1: Outside Passer',
                        fen: '4k3/5ppp/4p3/1p6/8/PP6/4KPPP/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10528319',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                ],
            },
            {
                cohort: '1100-1200',
                positions: [
                    {
                        title: '#2: Sveshnikov-Kasparov 1979',
                        fen: '8/5p2/4p1p1/4P2p/5P1P/kp4P1/P7/1K6 w - - 0 44',
                        link: '//www.chess.com/emboard?id=10531257',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                ],
            },
            {
                cohort: '1200-1300',
                positions: [
                    {
                        title: '#3: Topalov-Anand 2014 WC',
                        fen: '8/5pkp/6p1/1R6/2r5/4P3/4KPPP/8 w - - 0 28',
                        link: '//www.chess.com/emboard?id=10528357',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                ],
            },
            {
                cohort: '1300-1400',
                positions: [
                    {
                        title: '#4: Winter-Capablanca 1919',
                        fen: 'r4rk1/ppp5/3b1p1p/2p1p1p1/4P3/3P1PBP/PPP2P2/R4RK1 w - - 0 16',
                        link: '//www.chess.com/emboard?id=10528363',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                ],
            },
            {
                cohort: '1400-1500',
                positions: [
                    {
                        title: '#5: Petrosian-Ivkov 1982',
                        fen: '2r2rk1/pp2n1b1/3p1npp/3Ppp2/N3P3/4BP2/PP3NPP/R3K2R w KQ - 1 16',
                        link: '//www.chess.com/emboard?id=10528367',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#6: Larsen-Spassky 1968',
                        fen: '3rr3/4kppp/p7/1ppR4/4n3/P3PN1P/1P3PP1/2R2K2 w - - 2 24',
                        link: '//www.chess.com/emboard?id=10528371',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                ],
            },
            {
                cohort: '1500-1600',
                positions: [
                    {
                        title: '#7: Gheorghiu-Olafsson 1969',
                        fen: '2b3k1/5ppp/p3p3/1p6/1P1Pn3/4P3/1B2BPPP/6K1 w - - 0 21',
                        link: '//www.chess.com/emboard?id=10528383',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#8: Bogoljubov-Lasker 1925',
                        fen: '2r1bk2/pp4pp/3R4/4n3/4P3/5P2/PP4PP/3R2K1 w - - 0 24',
                        link: '//www.chess.com/emboard?id=10528389',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                ],
            },
            {
                cohort: '1600-1700',
                positions: [
                    {
                        title: '#9: Vaganian-Rashkovsky 1981',
                        fen: 'r4rk1/3npp1p/b2p2p1/3P4/2pnN3/6PP/P3PPBN/1R3RK1 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10528393',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#10: Andersson-Miles 1981',
                        fen: 'r1bnk2r/pp3pbp/4p1p1/8/8/2N1P1P1/PP3PBP/R1B1K2R w KQkq - 0 13',
                        link: '//www.chess.com/emboard?id=10528395',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                ],
            },
            {
                cohort: '1700-1800',
                positions: [
                    {
                        title: '#11: Fischer-Reshevsky 1963',
                        fen: 'r6r/1p1k3p/p2p1bp1/3Rp3/4P1P1/1PP5/1P3P2/2B1K2R w K - 0 22',
                        link: '//www.chess.com/emboard?id=10531265',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#12: Lautier-Karpov 1994',
                        fen: '4r1k1/6p1/3Rnp1p/8/3Pb3/5NPP/3B2n1/6K1 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10531269',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                ],
            },
            {
                cohort: '1800-1900',
                positions: [
                    {
                        title: '#13: Botvinnik-Alekhine 1938',
                        fen: '1n3rk1/2R3pp/pp3p2/3p4/3P4/5N2/PP3PPP/6K1 w - - 0 23',
                        link: '//www.chess.com/emboard?id=10531279',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#14: Znosko-Borovsky-Alekhine 1933',
                        fen: 'r2r2k1/1pp1bp1p/p6B/4p3/8/2P5/PP3PPP/R2R2K1 w - - 2 17',
                        link: '//www.chess.com/emboard?id=10531291',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#15: Gligoric-Smyslov 1953',
                        fen: '2rr2k1/p4ppp/1p2pn2/4p3/2P1P3/1PN3P1/P2R1PK1/R7 w - - 1 21',
                        link: '//www.chess.com/emboard?id=10531301',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                ],
            },
            {
                cohort: '1900-2000',
                positions: [
                    {
                        title: '#16: Smyslov-Benko 1969',
                        fen: 'rn3r2/p3ppkp/1p4p1/8/3N4/1P4P1/P3PPbP/R4RK1 w - - 0 15',
                        link: '//www.chess.com/emboard?id=10531353',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#17: Portisch-Smyslov 1981',
                        fen: 'r4rk1/1p3bpp/2p2p2/p3n3/Pb2P3/2N2PP1/1P2B2P/R1Bq1R1K w - - 0 23',
                        link: '//www.chess.com/emboard?id=10531369',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#18: Euwe-Smyslov 1948',
                        fen: '2r3k1/1p1npp1p/6p1/2nP4/4P3/rp2BP2/1R1KBP1P/1R6 w - - 4 23',
                        link: '//www.chess.com/emboard?id=10531377',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                ],
            },
            {
                cohort: '2000-2100',
                positions: [
                    {
                        title: '#19: Catalan Pressure',
                        fen: 'r1b1k2r/1p3ppp/pb2pn2/8/8/6P1/PP1BPPBP/RN3RK1 w kq - 0 15',
                        link: '//www.chess.com/emboard?id=10531381',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#20: Huebner-Smyslov 1968',
                        fen: 'r5k1/1p3p2/1B2p3/P1rpP2p/2b2P1p/8/1P3KP1/R7 w - - 0 33',
                        link: '//www.chess.com/emboard?id=10531395',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#21: Smyslov-Taimanov 1951',
                        fen: '6k1/5p1p/1p2p3/p1p3p1/P1Br4/6P1/1P3R1P/6K1 w - - 0 38',
                        link: '//www.chess.com/emboard?id=10531399',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                ],
            },
            {
                cohort: '2100-2200',
                positions: [
                    {
                        title: '#22: Smyslov-Barcza 1953',
                        fen: '2r3k1/1n2bpp1/3p1n1p/1N2p3/1P2P3/5N1P/1P3PP1/2B1R1K1 w - - 1 22',
                        link: '//www.chess.com/emboard?id=10531407',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#23: Mikenas-Smyslov 1944',
                        fen: '5k2/1p3ppb/2p4p/p7/P2bP1P1/1B1N1P2/1P5P/5K2 w - - 4 35',
                        link: '//www.chess.com/emboard?id=10531419',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#24: Gligoric-Smyslov 1959',
                        fen: '8/1pR3pk/5p1p/p1P1p3/4K1P1/P3P3/1r4P1/8 w - - 2 37',
                        link: '//www.chess.com/emboard?id=10531429',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                ],
            },
            {
                cohort: '2200-2300',
                positions: [
                    {
                        title: '#25: Smyslov-Simagin 1951',
                        fen: '8/2n2rkp/4p1p1/p1N3P1/1pP2P2/4PK2/P7/3R4 w - - 3 37',
                        link: '//www.chess.com/emboard?id=10531439',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#26: Smyslov-Simagin 1966',
                        fen: '8/3r1pkp/1p2pp2/8/nP1N4/4PKP1/5P1P/2R5 w - - 3 26',
                        link: '//www.chess.com/emboard?id=10531503',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#27: Evans-Smyslov 1978',
                        fen: '3r4/1p4pp/p4k2/3n1p2/2N5/1P3P2/P2P3P/3KR3 w - - 0 29',
                        link: '//www.chess.com/emboard?id=10531509',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#28: Smyslov-Beliavsky 1981',
                        fen: '8/pp3k1p/2r5/3R4/7P/1P6/P5P1/5K2 w - - 1 43',
                        link: '//www.chess.com/emboard?id=10531517',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                ],
            },
            {
                cohort: '2300-2400',
                positions: [
                    {
                        title: '#29: Smyslov-Silwa 1956',
                        fen: '1n3k2/1b4pp/1p3p2/1Pb1pP2/2N1P1P1/2BB1K1P/8/8 w - - 3 43',
                        link: '//www.chess.com/emboard?id=10531527',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#30: Smyslov-Magerramov 1989',
                        fen: '2b2bk1/1p2pp2/3n2p1/4N2p/p4P2/P2PK1P1/1B2P1BP/8 w - - 0 30',
                        link: '//www.chess.com/emboard?id=10531539',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#31: Smyslov-Euwe 1948',
                        fen: 'b7/3knp2/p2p2pb/1p1Pp2p/1B2P2P/1P1B1P2/P5P1/5NK1 w - - 1 41',
                        link: '//www.chess.com/emboard?id=10531545',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#32: Smyslov-Letelier 1950',
                        fen: '5rk1/pprb2pp/2n1pp2/P2pPn2/3P4/2BB1N2/2PK1PPP/R3R3 w - - 0 17',
                        link: '//www.chess.com/emboard?id=10531553',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                ],
            },
            {
                cohort: '2400+',
                positions: [
                    {
                        title: '#33: Smyslov-Haag 1963',
                        fen: '1kb3r1/ppp5/1nn1prpp/3p4/3P1P1P/1PN2NPB/P1P5/2KRR3 w - - 3 20',
                        link: '//www.chess.com/emboard?id=10531555',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#34: Goldin-Korzubov 1980',
                        fen: '6k1/pp3p2/6p1/3p4/2pN4/P1P2P1P/1P1q2P1/4R1K1 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10531565',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#35: Pritchett-Kagan 1968',
                        fen: '8/1p2p1kp/4p3/7p/8/5K2/1PP3P1/8 w - - 0 1',
                        link: '//www.chess.com/emboard?id=10531569',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                    {
                        title: '#36: Fischer-Taimanov 1971',
                        fen: '7r/3k1pp1/pp3n1p/2p1R3/5P2/6P1/PPP3BP/6K1 w - - 0 25',
                        link: '//www.chess.com/emboard?id=10531571',
                        limitSeconds: 300,
                        incrementSeconds: 30,
                    },
                ],
            },
        ],
    },
];
