/**
 * Represents the type of a Notification.
 */
export enum NotificationType {
    /** Notifications generated by comments on a game. */
    GameComment = 'GAME_COMMENT',
    NewFollower = 'NEW_FOLLOWER',
}

/**
 *  Data for a notification.
 */
export interface Notification {
    /** The id of the Notification. */
    id: string;

    /** The type of the Notification. */
    type: NotificationType;

    /** The time the Notification was last updated. */
    updatedAt: string;

    /** Metadata for a game comment Notification. */
    gameCommentMetadata?: {
        /** The cohort of the Game. */
        cohort: string;

        /** The id of the Game. */
        id: string;

        /** The headers of the Game. */
        headers: {
            [key: string]: string;
        };
    };

    /** Metadata for a new follower notification. */
    newFollowerMetadata?: {
        /** The username of the new follower. */
        username: string;

        /** The display name of the new follower. */
        displayName: string;

        /** The cohort of the new follower. */
        cohort: string;
    };
}

export function getTitle(notification: Notification): string {
    switch (notification.type) {
        case NotificationType.GameComment:
            return `${notification.gameCommentMetadata?.headers?.White} - ${notification.gameCommentMetadata?.headers?.Black}`;
        case NotificationType.NewFollower:
            return 'You have a new follower';
    }
}

export function getDescription(notification: Notification): string {
    switch (notification.type) {
        case NotificationType.GameComment:
            return 'There are new comments on your game.';
        case NotificationType.NewFollower:
            return `${notification.newFollowerMetadata?.displayName}`;
    }
}
