# Deploys the directory service.

service: chess-dojo-notify

plugins:
  - serverless-esbuild

package:
  individually: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  logRetentionInDays: 14
  environment:
    stage: ${sls:stage}
  httpApi:
    id: ${param:httpApiId}
  deploymentMethod: direct

  # TODO: on inserts into the database, queue into the SQS
functions:
  create:
    handler: create.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - NotificationQueue
              - Arn
  Resources:
    NotificationQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "NotificationQueue"
