AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  roundrobinapiv2

  Sample SAM Template for roundrobinapiv2

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 512

Resources:
  RoundRobinPlayerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: RoundRobinV2
      Handler: com.serverless.Handler::handleRequest
      Runtime: java21
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          CONNECTION_STRING: add connection string
          ENV: beta
      Events:
        Roundrobinevent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /player
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  RoundRobinApi:
    Description: "API Gateway endpoint URL for Prod stage for Round robin player function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/player/"
  RoundRobinPlayerFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt RoundRobinPlayerFunction.Arn
  RoundRobinPlayerFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt RoundRobinPlayerFunctionRole.Arn
