name: Cypress Tests

on: pull_request_target

jobs:
  cypress-run:
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm ci

      - name: Build Frontend
        working-directory: frontend
        run: npm run build:test

      - name: Cypress Run
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          build: npx cypress info
          start: npm run start:build
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 300
          record: false
        env:
          AWS_COGNITO_USERNAME: ${{ secrets.AWS_COGNITO_USERNAME }}
          AWS_COGNITO_PASSWORD: ${{ secrets.AWS_COGNITO_PASSWORD }}

      - name: Save Cypress Screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: frontend/cypress/screenshots
      
      - name: Check Coverage
        working-directory: frontend
        run: npx nyc report --reporter=text-summary

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: frontend/coverage
